# Generated by Django 4.2.7 on 2023-11-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_password_user_password1_user_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('skill1', models.CharField(max_length=100)),
                ('skill2', models.CharField(max_length=100)),
                ('skill3', models.CharField(max_length=100)),
                ('profile_img', models.ImageField(upload_to='')),
                ('background_img', models.ImageField(upload_to='')),
                ('profession', models.CharField(max_length=100)),
                ('overview', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('portfolio', models.CharField(max_length=100)),
                ('role1', models.CharField(max_length=100)),
                ('role_info', models.CharField(max_length=100)),
                ('role2', models.CharField(max_length=100)),
                ('role2_info', models.CharField(max_length=100)),
                ('role3', models.CharField(max_length=100)),
                ('role3_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
