# Generated by Django 4.2.7 on 2023-11-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_detail_overview_alter_detail_role2_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detail',
            old_name='role_info',
            new_name='role1_info',
        ),
        migrations.AlterField(
            model_name='detail',
            name='background_img',
            field=models.ImageField(upload_to='uploads/background/'),
        ),
        migrations.AlterField(
            model_name='detail',
            name='profile_img',
            field=models.ImageField(upload_to='uploads/profile/'),
        ),
    ]
